import FeaturedImages from '@/components/FeaturedImages'
import HeroSection from '@/components/HeroSection'
import { ArrowLeft, ArrowRight, Rounded, SliderLine } from '@/components/Icon'
import Navbar from '@/components/Navbar'
import Slider from 'react-slick'
import Head from 'next/head'
import 'slick-carousel/slick/slick.css'
import 'slick-carousel/slick/slick-theme.css'
import { imgSlider } from '@/data'
import { useState } from 'react'
import ExploreSection from '@/components/ExploreSection'

export default function Home() {
  const [slide, setSlide] = useState(null)

  const settings = {
    slidesToShow: 1,
    slidesToScroll: 1,
    infinite: true,
    speed: 500,
    autoplaySpeed: 2000,
    autoplay: true,
    arrows: false,
  }
  return (
    <>
      <Head>
        <title>Artsy Website</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <>
        <Navbar />
        <main className='mb-[34.09px] md:mb-[130px]'>
          <HeroSection />
        </main>
        <div className='mb-[112.99px] px-8 md:px-0 lg:mb-[169px]'>
          <div className='flex justify-center'>
            <img className='md:hidden' src='../images/hero_mobile.png' alt='' />
          </div>

          <div className='hidden md:flex gap-[20px] '>
            <div className='flex flex-row items-center'>
              <img
                className='object-cover '
                src='../images/desktop_hero/hero_one.png'
                alt=''
              />
            </div>
            <div>
              <img
                className='object-cover'
                src='../images/desktop_hero/hero_two.png'
                alt=''
              />
            </div>
            <div className='flex flex-row items-start -mt-10'>
              <img
                className='object-cover '
                src='../images/desktop_hero/hero_three.png'
                alt=''
              />
            </div>
            <div>
              <img
                className='object-cover  '
                src='../images/desktop_hero/hero_four.png'
                alt=''
              />
            </div>
            <div>
              <img
                className='object-cover '
                src='../images/desktop_hero/hero_five.png'
                alt=''
              />
            </div>
          </div>
        </div>
        <div className='mb-[6.25rem] pl-2 pr-[18px] md:px-12 lg:pl-[120px] lg:pr-[133px] lg:mb-[12.5]'>
          <h2 className='font-satoshi font-bold text-[28px] leading-[44px] mb-[30px] text-menu-color md:mb-[37px] lg:text-[48px] lg:leading-[65px]'>
            Featured products
          </h2>
          <div className='hidden lg:flex lg:border lg:border-b-[0.5px] lg:border-[#333333] lg:mb-[37px]'></div>
          <div>
            <div className='mb-[40px]'>
              <FeaturedImages
                imgMobile={'../images/featured_image/featured_one.png'}
                imgDesktop={'../images/featured_image/featured_one_desktop.png'}
                titleOne={'Boolean Egyptian'}
                titleTwo={'The Boolean Egyptian'}
                content={` Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam,
                purus sit amet luctus venenatis, lectus magna fringilla urna,
                porttitor rhoncus dolor pur`}
                imgContent={'64 major creators'}
              />
            </div>
            <div className='w-[294px] md:w-full border border-b-[0.5px] border-[#333333] mb-[37px] lg:mb-[61px] '></div>
            <div className='mb-[40px]'>
              <FeaturedImages
                imgMobile={'../images/featured_image/featured_two.png'}
                imgDesktop={'../images/featured_image/featured_two_desktop.png'}
                titleOne={'Boolean Egyptian'}
                titleTwo={'The Boolean Egyptian'}
                content={` Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam,
                purus sit amet luctus venenatis, lectus magna fringilla urna,
                porttitor rhoncus dolor pur`}
                imgContent={'64 major creators'}
                reverse={true}
              />
            </div>
            <div className='w-[294px] md:w-full border border-b-[0.5px] border-[#333333] mb-[37px] lg:mb-[61px]'></div>
            <div className='mb-[40px]'>
              <FeaturedImages
                imgMobile={'../images/featured_image/featured_three.png'}
                imgDesktop={
                  '../images/featured_image/featured_three_desktop.png'
                }
                titleOne={'Boolean Egyptian'}
                titleTwo={'The Boolean Egyptian'}
                content={` Lorem ipsum dolor sit amet, consectetur adipiscing elit ut aliquam,
                purus sit amet luctus venenatis, lectus magna fringilla urna,
                porttitor rhoncus dolor pur`}
                imgContent={'64 major creators'}
              />
            </div>
          </div>
        </div>
        <div className='relative bg-event-slider h-full pb-[34px] bg-cover bg-no-repeat mb-[100px] lg:h-[48.75rem] lg:bg-event-slider_desktop lg:mb-[100px]'>
          <div className='flex flex-col gap-[2.0625rem] lg:gap-[7.3125rem] lg:mb-[1.875rem]'>
            <div className='hidden lg:flex lg:flex-col lg:px-[7.5rem]'>
              <h2 className='pt-[25px] font-satoshi font-medium text-[2.5rem] leading-[54px] text-white'>
                See Upcoming Auctions and Exhibitions
              </h2>
              <div className='border border-b-[0.8px] border-white w-[667px] ml-4'></div>
            </div>
          </div>
          <div className='mt-[33px] mb-[21px] lg:mt-0'>
            <div className='relative bg-event-sub-img bg-cover bg-no-repeat h-full py-[33px] pl-[11px] mx-[34px] md:pl-[22px] md:pr-[22px] lg:h-[546px] lg:bg-event-sub_desktop lg:pt-[299px] lg:mx-[120px] '>
              <div>
                <Slider ref={setSlide} {...settings}>
                  {imgSlider.map((eventSlide) => {
                    const { id, title, number, date, content, link, reminder } =
                      eventSlide
                    return (
                      <div className='pl-2 pt-[33px]' key={id}>
                        <div className='flex flex-row gap-[29.03px] mb-[26px]'>
                          <Rounded />
                          <p className='font-bellefair font-normal text-[20px] text-white leading-[25px] w-[248px] tracking-normal md:w-full md:text-[30px]'>
                            {title}
                          </p>
                        </div>
                        <div className='flex flex-row gap-3'>
                          <div>
                            <p className='font-bellefair font-normal text-[45px] leading-[46px] text-[#e1e1e1] md:text-[50px]'>
                              {number}
                            </p>
                          </div>
                          <div className='flex flex-col lg:flex-row lg:items-center lg:gap-[118.08px]'>
                            <div className='flex flex-col gap-[20px]'>
                              <p className='font-poppins font-lighter text-xs leading-[18px] text-white uppercase tracking-widest md:text-sm'>
                                {date}
                              </p>
                              <p className='font-satoshi font-normal text-[10px] tracking-[0.065em] uppercase text-white leading-[20px] w-[287px] md:text-base md:w-full lg:w-[628.85px]'>
                                {content}
                              </p>
                            </div>
                            <div className='flex flex-row justify-end gap-[36px]'>
                              <button className='font-satoshi font-normal text-sm leading-[19px] underline text-white tracking-wide md:text-base'>
                                {link}
                              </button>
                              <button className='font-satoshi font-normal text-sm leading-[19px]  text-white tracking-wide border border-white px-[6px] py-[8px] rounded-[10px] md:text-base lg:py-[15px] lg:px-[13px] '>
                                {reminder}
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    )
                  })}
                </Slider>
              </div>
            </div>
          </div>
          <div className='hidden lg:flex lg:flex-row lg:justify-between lg:items-center lg:px-[7.5rem]'>
            <div className=''>
              <SliderLine />
            </div>
            <div className='flex flex-row items-center'>
              <button onClick={slide?.slickPrev}>
                <ArrowLeft />
              </button>
              <button onClick={slide?.slickNext}>
                <ArrowRight />
              </button>
            </div>
          </div>
        </div>
        <div className='mb-[20rem] lg:mb-[180px]'>
          <div className='border-[0.5px] border-black'></div>
          <ExploreSection title='Explore marketplace' />
          <div className='border-[0.5px] border-black'></div>
          <ExploreSection title='See auctions' />
          <div className='border-[0.5px] border-black'></div>
        </div>
      </>
    </>
  )
}
